### ISSUE TITLE
fyi, I ported your AabbTree to c# for use with Godot

### ISSUE THREAD

**Issue by jasonswearingen** [Sopiro/Muli#4]
https://github.com/jasons-godot-interesting-repos/Sopiro-Muli/blob/master/AabbTree.cs

just a heads up.   it works great.  Porting took me about 10 or 12 hrs.   feel free to close this after you read :)

**Comment by jasonswearingen** [comment]
oh also, can I ask what Node's `bool moved;` values are for?  it's not used inside the aabb tree, but seems like it could be useful for tick based updates.

**Comment by Sopiro** [comment]
Glad to hear your port is working well! 

The `moved` flag gets updated whenever a new AABB is added to the tree or an existing AABB is moved(re-inserted) due to a MoveNode(). One use case in my engine is during the broad phase for updating contact pairs:

https://github.com/Sopiro/Muli/blob/8720cf12be9a4b7d4e4e1927a001ac399b5d1e10/src/collision/broad_phase.cpp#L132-L136

**Comment by jasonswearingen** [comment]
got it, thank you, i'll leave the .moved as is then :)
